### ISSUE TITLE
results diffrent; bugs discovered.

### ISSUE THREAD

**Issue by lawlict** [iiscleap/DIHARD-2019-baseline#2]
Hello, 
    I run the baseline system on dihard-2019-dev dataset and get a DER of 23.6%, which is about 3% higher than the results you provide. My kaldi version is latest. Attachment is my result. 
[results.txt](https://github.com/iiscleap/DIHARD-2019-baseline/files/2935311/results.txt)

    In addition, some bugs are discovered:
1. run_notrain.sh: nnet_dir is not declared.
2. local/make_dihard_2018_dev.py: since the directory of dihard-2019-dev dataset is a little different from that of dihard-2018-dev dataset, this script cannot run directly.

**Comment by iiscleap** [comment]
Hello lawlict,
Results were different as the results displayed in readme was of DIHARD 2018 dev earlier. Please check the readme now. Results on DIHARD 2019 dev is mentioned.
nnet_dir is declared now.
A custom made data preparation script (make_dihard_2019_dev_eval_alltracks.sh) for DIHARD 2019 is added and instructions are updated to avoid path issues, thus making the script run directly now.

**Comment by lawlict** [comment]
I see it. Thank you for your work.
